"""Render a `CrewSpec` as a real CrewAI project on disk.

Building a crew in memory is enough to run it once. Writing it out is what makes
it yours: the generated project uses the standard `config/agents.yaml` +
`config/tasks.yaml` + `@CrewBase` layout, so the result is an ordinary CrewAI
codebase a human can edit, review and check into git — not an opaque blob the
factory has to regenerate every time.

`blueprint.json` is written alongside it so the same crew can be rebuilt in
memory later without another trip to the model.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from agent_factory.schema import CrewSpec

__all__ = ["write_project"]


def _agents_yaml(spec: CrewSpec) -> str:
    payload = {
        agent.name: {
            "role": agent.role,
            "goal": agent.goal,
            "backstory": agent.backstory,
        }
        for agent in spec.agents
    }
    return yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=88)


def _tasks_yaml(spec: CrewSpec) -> str:
    payload: dict[str, dict[str, object]] = {}
    for task in spec.tasks:
        entry: dict[str, object] = {
            "description": task.description,
            "expected_output": task.expected_output,
            "agent": task.agent,
        }
        if task.context:
            entry["context"] = list(task.context)
        if task.output_file:
            entry["output_file"] = task.output_file
        if task.markdown:
            entry["markdown"] = True
        payload[task.name] = entry
    return yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=88)


def _crew_py(spec: CrewSpec) -> str:
    """Emit an idiomatic `@CrewBase` module.

    `@CrewBase` resolves each task's `agent:` and `context:` YAML keys against
    the decorated method names, so the method names below must stay in step with
    the YAML keys.
    """
    lines: list[str] = [
        '"""',
        f"{spec.name} — generated by agent_factory.",
        "",
        *_wrap(spec.description, width=76),
        "",
        "Edit this file and the YAML in config/ freely; it is a normal CrewAI",
        "project. Regenerating from the blueprint will overwrite both.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from crewai import Agent, Crew, PlanningConfig, Process, Task",
        "from crewai.project import CrewBase, agent, crew, task",
        "",
        "from agent_factory.config import WORKER_MODEL, build_llm",
        "from agent_factory.registry import default_registry",
        "",
        "REGISTRY = default_registry()",
        "",
        "",
        "@CrewBase",
        f"class {_class_name(spec.name)}:",
        f'    """{spec.description.strip()[:200]}"""',
        "",
        '    agents_config = "config/agents.yaml"',
        '    tasks_config = "config/tasks.yaml"',
        "",
        "    def __init__(self, verbose: bool = True) -> None:",
        "        self.verbose = verbose",
        "        self.llm = build_llm(WORKER_MODEL)",
        "",
    ]

    for agent_spec in spec.agents:
        tools = ", ".join(repr(t) for t in agent_spec.tools)
        planning = "PlanningConfig()" if agent_spec.planning else "None"
        lines += [
            "    @agent",
            f"    def {agent_spec.name}(self) -> Agent:",
            "        return Agent(",
            f'            config=self.agents_config["{agent_spec.name}"],',
            f"            tools=REGISTRY.build([{tools}]),",
            f"            allow_delegation={agent_spec.allow_delegation},",
            f"            planning_config={planning},",
            f"            max_iter={agent_spec.max_iter},",
            "            llm=self.llm,",
            "            verbose=self.verbose,",
            "        )",
            "",
        ]

    for task_spec in spec.tasks:
        lines += [
            "    @task",
            f"    def {task_spec.name}(self) -> Task:",
            f'        return Task(config=self.tasks_config["{task_spec.name}"])',
            "",
        ]

    if spec.process == "hierarchical":
        process_line = "            process=Process.hierarchical,"
        manager_line = "            manager_llm=self.llm,"
    else:
        process_line = "            process=Process.sequential,"
        manager_line = None

    lines += [
        "    @crew",
        "    def crew(self) -> Crew:",
        "        return Crew(",
        f'            name="{spec.name}",',
        "            agents=self.agents,",
        "            tasks=self.tasks,",
        process_line,
    ]
    if manager_line:
        lines.append(manager_line)
    lines += [
        "            verbose=self.verbose,",
        "        )",
        "",
        "",
        'if __name__ == "__main__":',
        "    inputs = {",
    ]
    for placeholder in sorted(spec.placeholders()):
        lines.append(f'        "{placeholder}": "TODO: supply a value",')
    lines += [
        "    }",
        f"    result = {_class_name(spec.name)}().crew().kickoff(inputs=inputs)",
        "    print(result.raw)",
        "",
    ]
    return "\n".join(lines)


def _class_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_")) or "GeneratedCrew"


def _wrap(text: str, width: int) -> list[str]:
    import textwrap

    return textwrap.wrap(text.strip(), width=width) or [""]


def write_project(spec: CrewSpec, out_dir: Path | str = "generated") -> Path:
    """Write the crew to `<out_dir>/<crew name>/` and return that directory."""
    root = Path(out_dir) / spec.name
    (root / "config").mkdir(parents=True, exist_ok=True)

    (root / "config" / "agents.yaml").write_text(_agents_yaml(spec), encoding="utf-8")
    (root / "config" / "tasks.yaml").write_text(_tasks_yaml(spec), encoding="utf-8")
    (root / "crew.py").write_text(_crew_py(spec), encoding="utf-8")
    (root / "blueprint.json").write_text(
        spec.model_dump_json(indent=2), encoding="utf-8"
    )
    (root / "__init__.py").write_text("", encoding="utf-8")
    return root
